<?php
// Include Composer's autoloader for PHPMailer and dompdf
require 'vendor/autoload.php';

// Import the necessary classes
use Dompdf\Dompdf;
use Dompdf\Options;
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

// Step 1: Generate PDF using dompdf
// Initialize dompdf with options
$options = new Options();
$options->set('isHtml5ParserEnabled', true);  // Enable HTML5 support
$options->set('isPhpEnabled', true);  // Allow PHP functions (like `image()` and `date()`)

// Create an instance of dompdf
$dompdf = new Dompdf($options);

// HTML content for the PDF
$html = '
    <html>
        <head>
            <style>
                body {
                    font-family: Arial, sans-serif;
                    font-size: 14px;
                }
                h1 {
                    color: #4CAF50;
                }
                .content {
                    margin-top: 20px;
                }
            </style>
        </head>
        <body>
            <h1>Hello, World!</h1>
            <p>This is a PDF generated using dompdf and sent via email using PHPMailer.</p>
            <div class="content">
                <p>More content can go here.</p>
            </div>
        </body>
    </html>
';

// Load HTML into dompdf
$dompdf->loadHtml($html);

// (Optional) Set paper size (A4 is default)
$dompdf->setPaper('A4', 'portrait');

// Render PDF (first pass to process HTML and CSS)
$dompdf->render();

// Step 2: Get the PDF content
$pdfContent = $dompdf->output();  // Get the PDF content as a string

// Step 3: Send the PDF via PHPMailer
$mail = new PHPMailer(true);  // Create an instance of PHPMailer

try {
    //Server settings
    $mail->isSMTP();  // Use SMTP
    $mail->Host = 'smtp.example.com';  // Set the SMTP server to use
    $mail->SMTPAuth = true;
    $mail->Username = 'your_email@example.com';  // SMTP username
    $mail->Password = 'your_email_password';  // SMTP password
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;  // Enable TLS encryption
    $mail->Port = 587;  // TCP port to connect to (587 for TLS)

    //Recipients
    $mail->setFrom('your_email@example.com', 'Your Name');  // Sender's email
    $mail->addAddress('recipient@example.com', 'Recipient Name');  // Recipient's email

    // Attach the PDF generated by dompdf
    $mail->addStringAttachment($pdfContent, 'example.pdf', 'base64', 'application/pdf');

    // Content
    $mail->isHTML(true);  // Set email format to HTML
    $mail->Subject = 'Here is the PDF file';
    $mail->Body    = 'This email contains a PDF generated by dompdf and sent via PHPMailer.';

    // Send the email
    $mail->send();
    echo 'Message has been sent successfully!';
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}
?>
